import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
normal = { family = "MesloLGS Nerd Font" }

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[selection]
save_to_clipboard = true

[window]
decorations = "Transparent"

[window.padding]
x = 8
y = 30
