
ndpi:
	brew install coreutils gcc git gettext flex bison libtool autoconf automake pkg-config libpcap json-c pcre2 libmaxminddb rrdtool

exec:
	brew install luarocks
	luarocks install ltui
	luarocks install lua-pcap
	lua netcap.lua

inspect:
	brew install luarocks
	luarocks install ljndpi
	lua inspect.lua
